site_name: Bane NOR - Knowledge sharing
site_description: Bane NOR - Knowledge sharing

nav:
  - Overview:
    - Home: index.md
  - Integration:
    - Home:  integration/index.md
    - Quick Start: integration/quick-start.md
    - Strategy: integration/strategy.md
    - Terms & Definitions: integration/terms-and-definitions.md
    - Architecture: integration/architecture.md
    - API Management:
      - Home: integration/apim/index.md
      - Getting Started: 
        - Home: integration/apim/getting-started/index.md
        - Manage API Access Groups: integration/apim/howto/manage-api-access-groups.md
        - Add Open API Specification: integration/apim/howto/add-open-api-spec.md
      - API Security:
        - Overview: integration/apim/security/overview.md
        - Subscription Keys: integration/apim/security/subscription-keys.md
        - Maskinporten: integration/apim/security/maskinporten.md
    - Event Driven:
      - Home: integration/event-driven/index.md
      - Getting Started: 
        - Home: integration/event-driven/getting-started/index.md
        - Azure Event Hub: integration/event-driven/getting-started/eventhub.md
    - Guidelines:
      - Integration: integration/guidelines/integration.md
      - Kafka Guidelines: integration/guidelines/kafka-guidelines.md
      - Naming: integration/guidelines/naming.md
      - Event Modeling: integration/guidelines/event-modeling.md
    - Release Notes:
      - Release Notes: integration/release-notes/index.md
      - Component Changelog: integration/release-notes/changelog.md
  - Business:
    - Domain Driven: business/domain-driven.md
    - Abbreviations: business/abbreviations.md
    - Use Cases:
      - HitRail - Common Interface: business/use-cases/hitrail.md
  - FAQ: faq/index.md

theme:
  name: material
  logo: img/baneNOR-logo.svg
  favicon: img/baneNOR-favicon.png # located here: https://www.banenor.no/Resources/Favicon/favicon-32x32.png
  include_search_page: false
  search_index_only: true
  language: en
  font:
    text: Roboto
    code: Roboto Mono
  # icon:
    # logo: logo
  palette:
    - media: "(prefers-color-scheme: light)"
      scheme: default
      primary: indigo
      accent: deep orange
      toggle:
        icon: material/lightbulb
        name: Switch to dark mode

    - media: "(prefers-color-scheme: dark)"
      scheme: slate
      primary: light blue
      accent: deep orange
      toggle:
        icon: material/lightbulb-outline
        name: Switch to light mode

  features:
    - toc.follow
    - content.code.annotate
    - content.tooltips
    - search.suggest
    - search.highlight
    - search.share
    - content.tabs.link
    - navigation.instant
    - navigation.indexes
    - navigation.top
    - navigation.tabs
    - navigation.tabs.sticky
    - navigation.tracking

plugins:
  - search:
      lang: en
  - git-revision-date-localized:
      enable_creation_date: true
      type: timeago
      #exclude:
      #  - deployment/allowed-registries.md
  - glightbox
  # - minify:
      # minify_html: true

extra:
  generator: false
  search:
    language: "en"

  # alternate:
  #   - name: English
  #     link: /
  #     lang: en

markdown_extensions:
  - footnotes
  - attr_list
  - def_list
  - md_in_html
  - admonition
  - abbr
  - tables
  - pymdownx.details
  - pymdownx.superfences:
      preserve_tabs: true
      custom_fences:
        - name: mermaid
          class: mermaid
          format: !!python/name:pymdownx.superfences.fence_code_format
  - pymdownx.highlight:
      use_pygments: true
      linenums: true
      linenums_style: pymdownx-inline
      anchor_linenums: true
  - pymdownx.inlinehilite
  - pymdownx.tabbed:
      alternate_style: true
  - pymdownx.emoji:
      emoji_generator: !!python/name:pymdownx.emoji.to_svg
  - pymdownx.caret
  - pymdownx.tilde
  - pymdownx.mark
  - pymdownx.tilde
  - pymdownx.critic
  - pymdownx.keys
  - pymdownx.smartsymbols
  - pymdownx.tasklist:
      custom_checkbox: true
  - pymdownx.snippets:
      auto_append:
        - includes/abbreviations.md
  - toc:
      permalink: true

extra_css:
  - vendor/custom.css
