name: Create Release

on:
  push:
    tags:
      - "v*"

permissions:
  contents: read

jobs:
  release:
    permissions:
      contents: write
      actions: read

    runs-on: ubuntu-latest

    steps:
      - uses: actions/create-github-app-token@v2
        id: app-token
        with:
          app-id: ${{ vars.BN_RELEASER_APP_ID }}
          private-key: ${{ secrets.BN_RELEASER_PRIVATE_KEY }}

      - name: Checkout code
        uses: actions/checkout@v4

      - name: Create release
        env:
          GH_TOKEN: ${{ steps.app-token.outputs.token }}
        run: |
          TAG_NAME="${GITHUB_REF_NAME}"
          RELEASE_NAME="${TAG_NAME#v}"
          
          gh release create "$TAG_NAME" \
            --repo="$GITHUB_REPOSITORY" \
            --title "$RELEASE_NAME" \
            --generate-notes